apiVersion: v1
kind: ConfigMap
metadata:
  name: curator-config
data:
  action_file.yml: |-
    ---
    [{"filtertype":"age","source":"creation_date","direction":"older","unit":"days","unit_count":0}]
    actions:
      1:
        action: delete_indices
        description: "Clean up ES by deleting old indices"
        options:
          timeout_override:
          continue_if_exception: True
          disable_action: False
          ignore_empty_list: True
        filters:
        - filtertype: age
          source: create_date
          direction: older
          unit: days
          unit_count: 1
        - filtertype: kibana
          exclude: true
  config.yml: |-
    ---
    client:
      hosts:
        - elasticsearch.cattle-system
      port: 9200
      url_prefix:
      use_ssl: False
      certificate:
      client_cert:
      client_key:
      ssl_no_validate: False
      http_auth:
      timeout: 30
      master_only: False
    logging:
      loglevel: INFO
      logfile:
      logformat: default
      blacklist: ['elasticsearch', 'urllib3']